name: Build, Run, Deploy and Delete Docker Container

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          if docker build -t your-docker-image-tag .; then
            echo "Docker image built successfully."
          else
            echo "Error: Docker image build failed." >&2
            exit 1
          fi

      - name: Run Docker Container
        run: docker run -d --name my-container your-docker-image-tag

      - name: Stop Docker Container
        run: docker stop my-container

      - name: Remove Docker Container
        run: docker rm my-container
        if: always() 

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          content: .
          push: true
          tags: ceacaclaudiu/moviefinder:latest, ceacaclaudiu/moviefinder:${{ github.run_number }}